# Generated by Django 3.0.8 on 2020-08-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20200814_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Website',
            new_name='website',
        ),
    ]
