# Generated by Django 3.0.8 on 2020-08-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_auto_20200814_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
