# Generated by Django 3.0.8 on 2020-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_auto_20200814_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
